<?php
/**
 *
 *    This Module is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This Module is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this module.
 *    If not, see <http://www.gnu.org/licenses/>.
 *
 *    ProxiBlue is in no way affiliated to DoubleCLick.
 *    This module is not an officially endorsed module for magento by DoubleCLick
 * */
?>
<?php if ($this->getEnabled()): ?>
    <!--begin Flood Light Tags  code - module by proxiblue.com.au -->
        <iframe src="http://<?php echo $this->getMerchantCode(); ?>.<?php echo $this->getProdUrl(); ?>/activityi;<?php echo $this->getUrlParams(); ?>" width="1" height="1" frameborder="0" style="display:none"></iframe>
    <!--end Flood Light Tags code - module by proxiblue.com.au -->
<?php endif; ?>